server:
  port: 8081

spring:
  jpa:
    database: postgresql
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
#        default_schema: authorization_data
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

logging:
  level:
    com.me.storyhubuserregistrationbackend: TRACE

user-authenticator:
  user-repository:
    server-url: localhost:8080
    create-user-path: /user/create
    activate-user-path: /user/activate
    is-email-already-exists-path: /user/is-email-already-exists
    login-user: /user/login