spring:
  jpa:
    database: postgresql
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  #        default_schema: authorization_data
  datasource:
    platform: postgres
    url: jdbc:postgresql://ec2-54-246-92-116.eu-west-1.compute.amazonaws.com:5432/d2kpopai516dm6
    username: vihejvulteopty
    password: 49fd352cecd27e25c7b6275eb1a6f83f85b07a0a4d4c6ae385c9096ba27bda7a
    driver-class-name: org.postgresql.Driver

logging:
  level:
    com.me.storyhubuserregistrationbackend: TRACE

user-authenticator:
  user-repository:
    server-url: https://storyhub-user-repository.herokuapp.com
    create-user-path: /user/create
    activate-user-path: /user/activate
    is-email-already-exists-path: /user/is-email-already-exists
    user-credential: /user/{email}/credential