logging:
  level:
    com.me.storyhubuserregistrationbackend: TRACE

user-authenticator:
  user-repository:
    server-url: localhost:8080
    create-user-path: /user/create
    is-email-already-exists-path: /user/is-email-already-exists
server:
  port: 8081